# This is a basic workflow to help you get started with Actions

name: A Basic Workflow

# Controls (Triggers for the basic workflow) when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs called "build-app", "build-api", "build-db", and "package"
  # The jobs run in parallel by default, but you can define the order in which they run using the "needs" keyword.
  # Therefore, the "build-app" job will run first, followed by the "build-api" and "build-db" jobs, and finally the "package" job.
  # The "package" job will only run if the "build-app", "build-api", and "build-db" jobs complete successfully.
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world message running on ubuntu-latest runner!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building API on Windows latest runner!"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows!"

  package:
    needs: [build-app, build-api, build-db]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Packaging the application on Mac OS runner!"
